<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="frmAgregar.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="frmInformacion.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    </ItemGroup>

</Project>